content_show:
    path:     /{id}/show/{_format}
    defaults: { _controller: "PiZoneContentBundle:Content:show", _format: json }
    requirements:
        _format:  json|yml





content_delete:
    path:     /{id}/delete/{_format}
    defaults: { _controller: "PiZoneContentBundle:Content:delete", _format: json }
    methods:  [POST, DELETE]
    requirements:
        _format:  json|yml

