security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/api
            anonymous: ~
            form_login: false
            provider: fos_userbundle
            http_basic:
                realm: "REST Service Realm"

    access_control:
       - { path: ^/api/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/api/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/api/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/api/frontend, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/api, roles: ROLE_ADMIN, ips: %ip_access% }
       - { path: ^/api, roles: ROLE_NO_ACCESS }
       - { path: ^/efconnect, roles: ROLE_ADMIN, ips: %ip_access% }
       - { path: ^/efconnect, roles: ROLE_NO_ACCESS }
       - { path: ^/elfinder, roles: ROLE_ADMIN, ips: %ip_access% }
       - { path: ^/elfinder, roles: ROLE_NO_ACCESS }