security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        public:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path:  /user/login
                check_path:  /user/check
                default_target_path: /redirect_auth
            logout:
                path: /user/logout
            logout:       true
            anonymous:    true
        main:
            pattern: ^/
            form_login:
                login_path:  /login
                check_path:  /login_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                path: /logout
            anonymous:    true
            http_basic:
                realm: "REST Service Realm"
#        main:
#            pattern: ^/api
#            anonymous: ~
#            form_login:
#                provider: fos_userbundle
#                csrf_provider: form.csrf_provider
#            provider: fos_userbundle
#            http_basic:
#                realm: "REST Service Realm"

    access_control:
       - { path: ^/api/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/api/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/api/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/user/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/api/frontend, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/api, roles: ROLE_ADMIN, ips: %ip_access% }
       - { path: ^/api, roles: ROLE_NO_ACCESS }
       - { path: ^/efconnect, roles: ROLE_ADMIN, ips: %ip_access% }
       - { path: ^/efconnect, roles: ROLE_NO_ACCESS }
       - { path: ^/elfinder, roles: ROLE_ADMIN, ips: %ip_access% }
       - { path: ^/elfinder, roles: ROLE_NO_ACCESS }