menu_new:
    path:     /new/{_format}
    defaults: { _controller: "PiZoneMenuBundle:Menu/New:new", _format: json }
    requirements:
        _format:  json|yml

menu_create:
    path:     /create/{_format}
    defaults: { _controller: "PiZoneMenuBundle:Menu/New:create", _format: json }
    methods:  POST
    requirements:
        _format:  json|yml