web_item_delete:
    path:     /{id}/delete/{_format}
    defaults: { _controller: "PiZoneWebItemBundle:Action:delete", _format: json }
    requirements:
        id:       \d+
        _format:  json|xml