<?php

namespace PiZone\LayoutBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LayoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LayoutRepository extends EntityRepository{
    public function getActiveLayouts(){
        $q = $this->_em->createQueryBuilder();
        $query = $q->select("c")
            ->from("PiZoneLayoutBundle:Layout", "c")
            ->where('c.is_active = true');

        return $query;
    }
}
