parameters:
#    shop_frontend.example.class: Esser\FrontendBundle\Example

#services:
#    shop.form.registration:
#        class: Shop\FrontendBundle\Form\Type\RegistrationType
#        tags:
#            - { name: form.type, alias: shop_user_registration }
